name: cardio
channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - abseil-cpp=20211102.0
  - altair=4.1.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - certifi=2020.6.20
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - comm=0.1.2
  - commonmark=0.9.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.3
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - glog=0.5.0
  - grpc-cpp=1.46.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.13.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openpyxl=3.0.9
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - plotly=5.13.1
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=8.0.0
  - pycparser=2.21
  - pydeck=0.7.1
  - pygments=2.11.2
  - pympler=0.9
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - rich=12.5.1
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - semver=2.13.0
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.2.0
  - streamlit=1.16.0
  - tenacity=8.0.1
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - tzlocal=2.1
  - urllib3=1.26.14
  - utf8proc=2.6.1
  - validators=0.18.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cachecontrol==0.12.11
      - cython==0.29.33
      - h5py==3.8.0
      - hdmedians==0.14.2
      - lockfile==0.12.2
      - msgpack==1.0.5
      - natsort==8.3.1
      - scikit-bio==0.5.8
