# .streamlit/secrets.toml

metacard_drug_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1u4Y4pJ4a8lsPY0Ubw_h1ag8fATnP5u82sOGYdHZptqU/edit#gid=1607555461"
metacard_kegg_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1tMATYt0f7UL0Aj6pA3Gsdvnu5l-oxvg6hh7rKAeYvVI/edit#gid=1657881433"
metacard_metadata_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1t6mfVOJsSmbwtgvYzyYqT6ofSFoJb6HZBl2ZddZis4g/edit#gid=1481496480"
metacard_microbiome_public_gsheets_url = "https://docs.google.com/spreadsheets/d/13o6uYJ-vX1VIMPO1nkH4WYaNUJe3vdVrw6pv8O76S6g/edit#gid=1074439309"
metacard_serum_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1_Z_U_gJ0li1Iy7wwrQGWoZOcQ6fFc1As21omMuuObXc/edit#gid=1093748047"
metacard_taxonomy_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1lUUFKilps3PWizKqT63LMNzzYOOAlJn_pA7uxxaDY4k/edit#gid=2068094204"
metacard_urine_public_gsheets_url = "https://docs.google.com/spreadsheets/d/1iJ-qigjrBOkSna3pNooSfa6Mx2wu0Z1VJRcIQ6ksy_Q/edit#gid=1129391636"